[versions]
agp = "8.11.0"
kotlin = "2.2.0"
kotlinCoroutines = "1.10.1"
kotlinSerializtion = "2.0.21"
kotlinSerializtionJson = "1.8.0"
coreKtx = "1.15.0"
androidxLifecycle = "2.9.1"
composeBom = "2024.10.01"
activityCompose = "1.9.2"
androidxNavigation = "2.8.0"
androidTools = "31.1.3"
ksp = "2.2.0-2.0.2"
kermit = "2.0.4"
coil = "3.1.0"
ktorfit = "2.6.1"
ktor = "3.2.1"
room = "2.7.2"
sqlite = "2.5.2"
koinBom = "4.1.0"
roomGradlePlugin = "2.7.2"

[libraries]
# Kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name="kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name="kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-serializtion-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerializtionJson" }

# Android
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidxLifecycle" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-activity = { group = "androidx.compose.foundation", name = "foundation" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }

# Log
kermit = { group = "co.touchlab", name = "kermit", version.ref = "kermit" }

# Network
ktorfit-lib = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-lib", version.ref = "ktorfit" }
ktorfit-converters-call = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-converters-call", version.ref = "ktorfit" }
ktorfit-converters-response = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-converters-response", version.ref = "ktorfit" }
ktorfit-converters-flow = { group = "de.jensklingenberg.ktorfit", name = "ktorfit-converters-flow", version.ref = "ktorfit" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }

# Database
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
sqlite-bundled = { group = "androidx.sqlite", name = "sqlite-bundled", version.ref = "sqlite" }

# DI
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koinBom" }
koin-core = { group = "io.insert-koin", name = "koin-core" }
koin-android = { group = "io.insert-koin", name = "koin-android" }
koin-compose = { group = "io.insert-koin", name = "koin-compose" }
koin-compose-viewmodel = { group = "io.insert-koin", name = "koin-compose-viewmodel" }
koin-compose-viewmodel-navigation = { group = "io.insert-koin", name = "koin-compose-viewmodel-navigation" }

# Image
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }

# Dependencies of the included build-logic
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
compose-gradle-plugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }
androidx-room-gradle-plugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "roomGradlePlugin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serializtion = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerializtion" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
room = { id = "androidx.room", version.ref = "room" }
ktorfit = { id = "de.jensklingenberg.ktorfit", version.ref = "ktorfit" }

# Plugins defined by this project
convention-kmp-framework = { id = "convention.kmp.framework", version = "unspecified" }
convention-android-application = { id = "convention.android.application", version = "unspecified" }
convention-android-library = { id = "convention.android.library", version = "unspecified" }
convention-kmp-library = { id = "convention.kmp.library", version = "unspecified" }
convention-android-application-compose = { id = "convention.android.application.compose", version = "unspecified" }
convention-android-library-compose = { id = "convention.android.library.compose", version = "unspecified" }
convention-android-feature = { id = "convention.android.feature", version = "unspecified" }
convention-kmp-data = { id = "convention.kmp.data", version = "unspecified" }
convention-kmp-room = { id = "convention.kmp.room", version = "unspecified" }

[bundles]
common-base = [
    "kotlin-stdlib",
    "kotlin-coroutines-core",
    "kotlin-serializtion-json",

    "koin-core"
]

android-base = [
    "androidx-core-ktx",
    "androidx-lifecycle-runtime-ktx",

    "kotlin-coroutines-android",

    "koin-android"
]

android-compose = [
    "androidx-compose-ui",
    "androidx-compose-material3",
    "androidx-compose-material-icons-extended",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-foundation",
    "androidx-compose-foundation-layout",

    "androidx-lifecycle-runtime-compose",
    "androidx-lifecycle-viewmodel-compose",

    "androidx-navigation-compose",

    "koin-compose",
    "koin-compose-viewmodel",
    "koin-compose-viewmodel-navigation"
]