[versions]
agp = "8.3.1"
kotlin = "2.1.0"
kotlinCoroutines = "1.10.1"
kotlinSerializtion = "2.0.21"
kotlinSerializtionJson = "1.8.0"
coreKtx = "1.15.0"
lifecycleRuntimeKtx = "2.8.7"
composeBom = "2024.10.01"
activityCompose = "1.9.2"
androidxLifecycle = "2.8.5"
androidxNavigation = "2.8.0"
androidxHilt = "1.2.0"
androidTools = "31.1.3"
ksp = "2.1.0-1.0.29"
coil = "3.1.0"
retrofit = "2.11.0"
room = "2.7.1"
hilt = "2.56.1"

[libraries]
# Kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutines-android = { group = "org.jetbrains.kotlinx", name="kotlinx-coroutines-android", version.ref = "kotlinCoroutines" }
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name="kotlinx-coroutines-core", version.ref = "kotlinCoroutines" }
kotlin-serializtion-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerializtionJson" }

# Android
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-activity = { group = "androidx.compose.foundation", name = "foundation" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-hilt-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHilt" }

# Network
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
retrofit-converter-kotlinx-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit"}

# Database
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }

# DI
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

# Image
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }

# Dependencies of the included build-logic
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-tools-common = { group = "com.android.tools", name = "common", version.ref = "androidTools" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
compose-gradle-plugin = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serializtion = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerializtion" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

# Plugins defined by this project
convention-android-framework = { id = "convention.android.framework", version = "unspecified" }
convention-android-application = { id = "convention.android.application", version = "unspecified" }
convention-android-library = { id = "convention.android.library", version = "unspecified" }
convention-android-application-compose = { id = "convention.android.application.compose", version = "unspecified" }
convention-android-library-compose = { id = "convention.android.library.compose", version = "unspecified" }
convention-android-feature = { id = "convention.android.feature", version = "unspecified" }
convention-android-data = { id = "convention.android.data", version = "unspecified" }

[bundles]
common-base = [
    "kotlin-stdlib",
    "kotlin-coroutines-core",
    "kotlin-serializtion-json",
]

android-base = [
    "androidx-core-ktx",
    "androidx-lifecycle-runtime-ktx",

    "kotlin-coroutines-android",

    "hilt-android",
]

android-compose = [
    "androidx-compose-ui",
    "androidx-compose-material3",
    "androidx-compose-material-icons-extended",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-foundation",
    "androidx-compose-foundation-layout",

    "androidx-lifecycle-runtime-compose",
    "androidx-lifecycle-viewmodel-compose",

    "androidx-navigation-compose",

    "androidx-hilt-compose"
]